import { GLOBAL_CONSTRAINTS } from '../../common/constraints/global.constraints';

export const ROLE_CONSTRAINTS = {
    TITLE: {
        MIN_LENGTH: GLOBAL_CONSTRAINTS.TITLE.LENGTH.MIN,
        MAX_LENGTH: GLOBAL_CONSTRAINTS.TITLE.LENGTH.MAX,
    },
    DESCRIPTION: {
        MIN_LENGTH: GLOBAL_CONSTRAINTS.DESCRIPTION.LENGTH.MIN,
        MAX_LENGTH: GLOBAL_CONSTRAINTS.DESCRIPTION.LENGTH.MAX,
    },
};
