version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: intra
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intra
    ports:
      # - "${DATABASE_PORT}:3306"
      - "3307:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge