export enum NotificationKind {
    RATEE_SELF_ASSESSMENT = 'RATEE_SELF_ASSESSMENT',
    RESPONDENT_INVITATION = 'RESPONDENT_INVITATION',
    HR_REPORT_READY = 'HR_REPORT_READY',
    REVIEWER_REPORT_READY = 'REVIEWER_REPORT_READY',
}
