import { GLOBAL_CONSTANTS } from "./global.constants";


export const CYCLE_CONSTANTS = {
    ANONYMITY_THRESHOLD: {
        MIN: GLOBAL_CONSTANTS.ANONYMITY_THRESHOLD.MIN,
    },
    TITLE: {
        MIN_LENGTH: GLOBAL_CONSTANTS.TITLE.MIN_LENGTH,
        MAX_LENGTH: GLOBAL_CONSTANTS.TITLE.MAX_LENGTH,
    },
    DESCRIPTION: {
        MIN_LENGTH: GLOBAL_CONSTANTS.DESCRIPTION.MIN_LENGTH,
        MAX_LENGTH: GLOBAL_CONSTANTS.DESCRIPTION.MAX_LENGTH,
    },
};
