import { GLOBAL_CONSTANTS } from "./global.constants";

export const QUESTION_CONSTANTS = {
  TITLE: {
    MIN_LENGTH: GLOBAL_CONSTANTS.DESCRIPTION.MIN_LENGTH,
    MAX_LENGTH: GLOBAL_CONSTANTS.DESCRIPTION.MAX_LENGTH,
  },
};

