import { GLOBAL_CONSTANTS } from './global.constants';

export const REVIEW_CONSTANTS = {
  TITLE: {
    MIN_LENGTH: GLOBAL_CONSTANTS.TITLE.MIN_LENGTH,
    MAX_LENGTH: GLOBAL_CONSTANTS.TITLE.MAX_LENGTH,
  },
  DESCRIPTION: {
    MIN_LENGTH: GLOBAL_CONSTANTS.DESCRIPTION.MIN_LENGTH,
    MAX_LENGTH: GLOBAL_CONSTANTS.DESCRIPTION.MAX_LENGTH,
  },
  NOTE: {
    MIN_LENGTH: GLOBAL_CONSTANTS.NOTE.MIN_LENGTH,
    MAX_LENGTH: GLOBAL_CONSTANTS.NOTE.MAX_LENGTH,
  },
  COMMENT: {
    MIN_LENGTH: GLOBAL_CONSTANTS.COMMENT.MIN_LENGTH,
    MAX_LENGTH: GLOBAL_CONSTANTS.COMMENT.MAX_LENGTH,
  },
};