import { GLOBAL_CONSTRAINTS } from '../../common/constraints/global.constraints';

export const REPORT_CONSTRAINTS = {
    RESPONDENT_COUNT: {
        MIN: GLOBAL_CONSTRAINTS.ANONYMITY_THRESHOLD.MIN,
    },
    TURNOUT_PERCENTAGE: {
        MIN: GLOBAL_CONSTRAINTS.PERCENTAGE.MIN,
        MAX: GLOBAL_CONSTRAINTS.PERCENTAGE.MAX,
    },
    SCORE: {
        MIN: GLOBAL_CONSTRAINTS.SCORE.MIN,
        MAX: GLOBAL_CONSTRAINTS.SCORE.MAX,
    },
    DELTA_PERCENTAGE: {
        MIN: GLOBAL_CONSTRAINTS.PERCENTAGE.MIN,
        MAX: GLOBAL_CONSTRAINTS.PERCENTAGE.MAX,
    },
};
