export enum StrategicReportSortField {
    ID = 'id',
    CYCLE_ID = 'cycleId',
    CYCLE_TITLE = 'cycleTitle',
    RATEE_COUNT = 'rateeCount',
    RATEE_IDS = 'rateeIds',
    RESPONDENT_COUNT = 'respondentCount',
    RESPONDENT_IDS = 'respondentIds',
    ANSWER_COUNT = 'answerCount',
    REVIEWER_COUNT = 'reviewerCount',
    REVIEWER_IDS = 'reviewerIds',
    TEAM_COUNT = 'teamCount',
    TEAM_IDS = 'teamIds',
    POSITION_COUNT = 'positionCount',
    POSITION_IDS = 'positionIds',
    COMPETENCE_COUNT = 'competenceCount',
    COMPETENCE_IDS = 'competenceIds',
    QUESTION_COUNT = 'questionCount',
    QUESTION_IDS = 'questionIds',
    TURNOUT_AVG_PCT_OF_RATEES = 'turnoutAvgPctOfRatees',
    TURNOUT_AVG_PCT_OF_TEAMS = 'turnoutAvgPctOfTeams',
    TURNOUT_AVG_PCT_OF_OTHERS = 'turnoutAvgPctOfOthers',
    COMPETENCE_GENERAL_AVG_SELF = 'competenceGeneralAvgSelf',
    COMPETENCE_GENERAL_AVG_TEAM = 'competenceGeneralAvgTeam',
    COMPETENCE_GENERAL_AVG_OTHER = 'competenceGeneralAvgOther',
    COMPETENCE_GENERAL_PCT_SELF = 'competenceGeneralPctSelf',
    COMPETENCE_GENERAL_PCT_TEAM = 'competenceGeneralPctTeam',
    COMPETENCE_GENERAL_PCT_OTHER = 'competenceGeneralPctOther',
    COMPETENCE_GENERAL_DELTA_TEAM = 'competenceGeneralDeltaTeam',
    COMPETENCE_GENERAL_DELTA_OTHER = 'competenceGeneralDeltaOther',
    CREATED_AT = 'createdAt',
}

export const STRATEGIC_REPORT_SOFT_FIELDS = Object.values(
    StrategicReportSortField,
);
