import { SortDirection } from '../../../common/enums/sort-direction.enum';
import { StrategicReportSortField } from '../../enums/strategic-report-sort-field.enum';

export type StrategicReportSearchQuery = {
    cycleId?: number;
    cycleTitle?: string;
    rateeCount?: number;
    rateeIds?: number[];
    respondentCount?: number;
    respondentIds?: number[];
    answerCount?: number;
    reviewerCount?: number;
    reviewerIds?: number[];
    teamCount?: number;
    teamIds?: number[];
    positionCount?: number;
    positionIds?: number[];
    competenceCount?: number;
    competenceIds?: number[];
    questionCount?: number;
    questionIds?: number[];
    turnoutAvgPctOfRatees?: number;
    turnoutAvgPctOfTeams?: number;
    turnoutAvgPctOfOthers?: number;
    competenceGeneralAvgSelf?: number;
    competenceGeneralAvgTeam?: number;
    competenceGeneralAvgOther?: number;
    competenceGeneralPctSelf?: number;
    competenceGeneralPctTeam?: number;
    competenceGeneralPctOther?: number;
    competenceGeneralDeltaTeam?: number;
    competenceGeneralDeltaOther?: number;
    createdAt?: Date;
    sortBy?: StrategicReportSortField;
    sortDirection?: SortDirection;
};
