export enum ReviewStage {
    NEW = 'NEW',
    SELF_ASSESSMENT = 'SELF_ASSESSMENT',
    WAITING_TO_START = 'WAITING_TO_START',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED',
    PREPARING_REPORT = 'PREPARING_REPORT',
    PROCESSING_BY_HR = 'PROCESSING_BY_HR',
    PUBLISHED = 'PUBLISHED',
    ANALYSIS = 'ANALYSIS',
    CANCELED = 'CANCELED',
    ARCHIVED = 'ARCHIVED',
}

export const REVIEW_STAGES = Object.values(ReviewStage);
