export enum ReviewStage {
  CANCELED = 'CANCELED',
  VERIFICATION_BY_HR = 'VERIFICATION_BY_HR',
  VERIFICATION_BY_USER = 'VERIFICATION_BY_USER',
  REJECTED = 'REJECTED',
  SELF_ASSESSMENT = 'SELF_ASSESSMENT',
  WAITING_TO_START = 'WAITING_TO_START',
  IN_PROGRESS = 'IN_PROGRESS',
  RESEARCH = 'RESEARCH',
  FINISHED = 'FINISHED',
}

export const REVIEW_STAGES = Object.values(ReviewStage);
