import {
    AnswerType,
    type AuthUser,
    type Cluster,
    type Competence,
    type Cycle,
    CycleStage,
    IdentityRole,
    IdentityStatus,
    type Position,
    type Question,
    type QuestionTemplate,
    QuestionTemplateStatus,
    type Respondent,
    RespondentCategory,
    ResponseStatus,
    type Review,
    ReviewStage,
    type Team,
    type User,
} from './types';

// =================== CURRENT USER ===================

export const currentUser: AuthUser = {
    id: 2,
    firstName: 'Anna',
    lastName: 'Boyko',
    fullName: 'Anna Boyko',
    email: 'anna.boyko@intra.com',
    avatarUrl: '',
    roles: [IdentityRole.HR, IdentityRole.ADMIN],
    positionTitle: 'HR Manager',
    teamTitle: 'People Operations',
};

// =================== USERS ===================

export const mockUsers: User[] = [
    {
        id: 1,
        firstName: 'Valerii',
        lastName: 'Velychko',
        fullName: 'Valerii Velychko',
        email: 'valerii.v@intra.com',
        status: IdentityStatus.ACTIVE,
        positionId: 1,
        positionTitle: 'Senior Backend Engineer',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        roles: [IdentityRole.EMPLOYEE],
        createdAt: '2025-01-10T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
    {
        id: 2,
        firstName: 'Anna',
        lastName: 'Boyko',
        fullName: 'Anna Boyko',
        email: 'anna.boyko@intra.com',
        status: IdentityStatus.ACTIVE,
        positionId: 3,
        positionTitle: 'HR Manager',
        teamId: 3,
        teamTitle: 'People Operations',
        roles: [IdentityRole.HR, IdentityRole.ADMIN],
        createdAt: '2024-11-01T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
    {
        id: 3,
        firstName: 'Ivanna',
        lastName: 'Bulava',
        fullName: 'Ivanna Bulava',
        email: 'ivanna.b@intra.com',
        status: IdentityStatus.ACTIVE,
        positionId: 2,
        positionTitle: 'Frontend Engineer',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        roles: [IdentityRole.EMPLOYEE],
        createdAt: '2025-02-15T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
    {
        id: 4,
        firstName: 'Oleksii',
        lastName: 'Koval',
        fullName: 'Oleksii Koval',
        email: 'oleksii.k@intra.com',
        status: IdentityStatus.ACTIVE,
        positionId: 4,
        positionTitle: 'Product Designer',
        teamId: 2,
        teamTitle: 'Design',
        managerId: 6,
        managerFullName: 'Maria Shevchenko',
        roles: [IdentityRole.EMPLOYEE],
        createdAt: '2025-03-01T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
    {
        id: 5,
        firstName: 'Yaroslav',
        lastName: 'Syvyi',
        fullName: 'Yaroslav Syvyi',
        email: 'yaroslav.s@intra.com',
        status: IdentityStatus.ACTIVE,
        positionId: 5,
        positionTitle: 'Engineering Manager',
        teamId: 1,
        teamTitle: 'Engineering',
        roles: [IdentityRole.MANAGER, IdentityRole.EMPLOYEE],
        createdAt: '2024-09-01T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
    {
        id: 6,
        firstName: 'Maria',
        lastName: 'Shevchenko',
        fullName: 'Maria Shevchenko',
        email: 'maria.s@intra.com',
        status: IdentityStatus.ACTIVE,
        positionId: 6,
        positionTitle: 'Design Lead',
        teamId: 2,
        teamTitle: 'Design',
        roles: [IdentityRole.MANAGER, IdentityRole.EMPLOYEE],
        createdAt: '2024-10-01T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
    {
        id: 7,
        firstName: 'Dmytro',
        lastName: 'Lysenko',
        fullName: 'Dmytro Lysenko',
        email: 'dmytro.l@intra.com',
        status: IdentityStatus.ACTIVE,
        positionId: 7,
        positionTitle: 'QA Engineer',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        roles: [IdentityRole.EMPLOYEE],
        createdAt: '2025-04-01T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
    {
        id: 8,
        firstName: 'Kateryna',
        lastName: 'Moroz',
        fullName: 'Kateryna Moroz',
        email: 'kateryna.m@intra.com',
        status: IdentityStatus.INACTIVE,
        positionId: 2,
        positionTitle: 'Frontend Engineer',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        roles: [IdentityRole.EMPLOYEE],
        createdAt: '2025-01-20T10:00:00Z',
        updatedAt: '2025-06-01T10:00:00Z',
    },
];

// =================== POSITIONS ===================

export const mockPositions: Position[] = [
    {
        id: 1,
        title: 'Senior Backend Engineer',
        description: 'Backend development, architecture design, code reviews',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 2,
        title: 'Frontend Engineer',
        description: 'Frontend development with React and Next.js',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 3,
        title: 'HR Manager',
        description: 'Human resources management and people operations',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 4,
        title: 'Product Designer',
        description: 'UX/UI design and product research',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 5,
        title: 'Engineering Manager',
        description: 'Leading engineering teams and technical strategy',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 6,
        title: 'Design Lead',
        description: 'Leading design team and design system',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 7,
        title: 'QA Engineer',
        description: 'Quality assurance and test automation',
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
];

// =================== TEAMS ===================

export const mockTeams: Team[] = [
    {
        id: 1,
        title: 'Engineering',
        description: 'Product engineering and development',
        headId: 5,
        headFullName: 'Yaroslav Syvyi',
        membersCount: 5,
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 2,
        title: 'Design',
        description: 'Product design and user experience',
        headId: 6,
        headFullName: 'Maria Shevchenko',
        membersCount: 2,
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
    {
        id: 3,
        title: 'People Operations',
        description: 'HR and people management',
        headId: 2,
        headFullName: 'Anna Boyko',
        membersCount: 1,
        createdAt: '2024-01-01T10:00:00Z',
        updatedAt: '2024-01-01T10:00:00Z',
    },
];

// =================== COMPETENCES ===================

export const mockCompetences: Competence[] = [
    {
        id: 1,
        code: 'COMM',
        title: 'Communication',
        description:
            'Ability to communicate effectively with team members and stakeholders',
        questionsCount: 4,
    },
    {
        id: 2,
        code: 'TECH',
        title: 'Technical Excellence',
        description: 'Technical skills and engineering best practices',
        questionsCount: 5,
    },
    {
        id: 3,
        code: 'LEAD',
        title: 'Leadership',
        description: 'Ability to lead, mentor and guide team members',
        questionsCount: 3,
    },
    {
        id: 4,
        code: 'COLLAB',
        title: 'Collaboration',
        description: 'Working effectively with others across teams',
        questionsCount: 3,
    },
    {
        id: 5,
        code: 'PROB',
        title: 'Problem Solving',
        description: 'Analytical thinking and creative problem solving',
        questionsCount: 2,
    },
];

// =================== CYCLES ===================

export const mockCycles: Cycle[] = [
    {
        id: 1,
        title: 'Q1 2026 Performance Review',
        description: 'First quarter 360 feedback cycle for all departments',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        stage: CycleStage.ACTIVE,
        isActive: true,
        minRespondentsThreshold: 3,
        startDate: '2026-01-01T00:00:00Z',
        endDate: '2026-03-31T00:00:00Z',
        reviewDeadline: '2026-01-15T00:00:00Z',
        approvalDeadline: '2026-01-20T00:00:00Z',
        responseDeadline: '2026-02-28T00:00:00Z',
        reviewsCount: 6,
        createdAt: '2025-12-15T10:00:00Z',
        updatedAt: '2026-01-02T10:00:00Z',
    },
    {
        id: 2,
        title: 'Q4 2025 Year-End Review',
        description: 'Annual year-end performance feedback cycle',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        stage: CycleStage.FINISHED,
        isActive: false,
        minRespondentsThreshold: 3,
        startDate: '2025-10-01T00:00:00Z',
        endDate: '2025-12-31T00:00:00Z',
        reviewDeadline: '2025-10-15T00:00:00Z',
        approvalDeadline: '2025-10-20T00:00:00Z',
        responseDeadline: '2025-11-30T00:00:00Z',
        reviewsCount: 8,
        createdAt: '2025-09-20T10:00:00Z',
        updatedAt: '2025-12-31T10:00:00Z',
    },
    {
        id: 3,
        title: 'Mid-Year Check-in 2025',
        description: 'Mid-year development feedback for engineering teams',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        stage: CycleStage.FINISHED,
        isActive: false,
        minRespondentsThreshold: 2,
        startDate: '2025-06-01T00:00:00Z',
        endDate: '2025-07-31T00:00:00Z',
        reviewsCount: 4,
        createdAt: '2025-05-15T10:00:00Z',
        updatedAt: '2025-08-01T10:00:00Z',
    },
];

// =================== REVIEWS ===================

export const mockReviews: Review[] = [
    {
        id: 1,
        rateeId: 1,
        rateeFullName: 'Valerii Velychko',
        rateePositionId: 1,
        rateePositionTitle: 'Senior Backend Engineer',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        managerPositionId: 5,
        managerPositionTitle: 'Engineering Manager',
        cycleId: 1,
        cycleTitle: 'Q1 2026 Performance Review',
        stage: ReviewStage.COLLECTING_RESPONSES,
        respondentsCount: 5,
        respondedCount: 3,
        createdAt: '2026-01-05T10:00:00Z',
        updatedAt: '2026-02-01T10:00:00Z',
    },
    {
        id: 2,
        rateeId: 3,
        rateeFullName: 'Ivanna Bulava',
        rateePositionId: 2,
        rateePositionTitle: 'Frontend Engineer',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        managerPositionId: 5,
        managerPositionTitle: 'Engineering Manager',
        cycleId: 1,
        cycleTitle: 'Q1 2026 Performance Review',
        stage: ReviewStage.VERIFICATION_BY_HR,
        respondentsCount: 4,
        respondedCount: 0,
        createdAt: '2026-01-05T10:00:00Z',
        updatedAt: '2026-01-10T10:00:00Z',
    },
    {
        id: 3,
        rateeId: 4,
        rateeFullName: 'Oleksii Koval',
        rateePositionId: 4,
        rateePositionTitle: 'Product Designer',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        teamId: 2,
        teamTitle: 'Design',
        managerId: 6,
        managerFullName: 'Maria Shevchenko',
        managerPositionId: 6,
        managerPositionTitle: 'Design Lead',
        cycleId: 1,
        cycleTitle: 'Q1 2026 Performance Review',
        stage: ReviewStage.DRAFT,
        respondentsCount: 3,
        respondedCount: 0,
        createdAt: '2026-01-06T10:00:00Z',
        updatedAt: '2026-01-06T10:00:00Z',
    },
    {
        id: 4,
        rateeId: 5,
        rateeFullName: 'Yaroslav Syvyi',
        rateePositionId: 5,
        rateePositionTitle: 'Engineering Manager',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        teamId: 1,
        teamTitle: 'Engineering',
        cycleId: 1,
        cycleTitle: 'Q1 2026 Performance Review',
        stage: ReviewStage.COLLECTING_RESPONSES,
        respondentsCount: 6,
        respondedCount: 4,
        createdAt: '2026-01-05T10:00:00Z',
        updatedAt: '2026-02-10T10:00:00Z',
    },
    {
        id: 5,
        rateeId: 7,
        rateeFullName: 'Dmytro Lysenko',
        rateePositionId: 7,
        rateePositionTitle: 'QA Engineer',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        managerPositionId: 5,
        managerPositionTitle: 'Engineering Manager',
        cycleId: 1,
        cycleTitle: 'Q1 2026 Performance Review',
        stage: ReviewStage.REPORT_READY,
        respondentsCount: 4,
        respondedCount: 4,
        reportId: 1,
        createdAt: '2026-01-05T10:00:00Z',
        updatedAt: '2026-02-15T10:00:00Z',
    },
    {
        id: 6,
        rateeId: 1,
        rateeFullName: 'Valerii Velychko',
        rateePositionId: 1,
        rateePositionTitle: 'Senior Backend Engineer',
        hrId: 2,
        hrFullName: 'Anna Boyko',
        teamId: 1,
        teamTitle: 'Engineering',
        managerId: 5,
        managerFullName: 'Yaroslav Syvyi',
        managerPositionId: 5,
        managerPositionTitle: 'Engineering Manager',
        cycleId: 2,
        cycleTitle: 'Q4 2025 Year-End Review',
        stage: ReviewStage.REPORT_READY,
        respondentsCount: 5,
        respondedCount: 5,
        reportId: 2,
        createdAt: '2025-10-05T10:00:00Z',
        updatedAt: '2025-12-01T10:00:00Z',
    },
];

// =================== RESPONDENTS ===================

export const mockRespondents: Respondent[] = [
    {
        id: 1,
        reviewId: 1,
        respondentId: 1,
        fullName: 'Valerii Velychko',
        category: RespondentCategory.SELF,
        responseStatus: ResponseStatus.RESPONDED,
        positionId: 1,
        positionTitle: 'Senior Backend Engineer',
        teamId: 1,
        teamTitle: 'Engineering',
        invitedAt: '2026-01-06T10:00:00Z',
        respondedAt: '2026-01-10T10:00:00Z',
    },
    {
        id: 2,
        reviewId: 1,
        respondentId: 3,
        fullName: 'Ivanna Bulava',
        category: RespondentCategory.TEAM,
        responseStatus: ResponseStatus.RESPONDED,
        positionId: 2,
        positionTitle: 'Frontend Engineer',
        teamId: 1,
        teamTitle: 'Engineering',
        invitedAt: '2026-01-06T10:00:00Z',
        respondedAt: '2026-01-15T10:00:00Z',
    },
    {
        id: 3,
        reviewId: 1,
        respondentId: 5,
        fullName: 'Yaroslav Syvyi',
        category: RespondentCategory.OTHER,
        responseStatus: ResponseStatus.RESPONDED,
        positionId: 5,
        positionTitle: 'Engineering Manager',
        teamId: 1,
        teamTitle: 'Engineering',
        invitedAt: '2026-01-06T10:00:00Z',
        respondedAt: '2026-01-12T10:00:00Z',
    },
    {
        id: 4,
        reviewId: 1,
        respondentId: 7,
        fullName: 'Dmytro Lysenko',
        category: RespondentCategory.TEAM,
        responseStatus: ResponseStatus.PENDING,
        positionId: 7,
        positionTitle: 'QA Engineer',
        teamId: 1,
        teamTitle: 'Engineering',
        invitedAt: '2026-01-06T10:00:00Z',
    },
    {
        id: 5,
        reviewId: 1,
        respondentId: 4,
        fullName: 'Oleksii Koval',
        category: RespondentCategory.OTHER,
        responseStatus: ResponseStatus.CANCELED,
        respondentNote: 'On leave',
        positionId: 4,
        positionTitle: 'Product Designer',
        teamId: 2,
        teamTitle: 'Design',
        invitedAt: '2026-01-06T10:00:00Z',
        canceledAt: '2026-01-08T10:00:00Z',
    },
];

// =================== QUESTION TEMPLATES ===================

export const mockQuestionTemplates: QuestionTemplate[] = [
    {
        id: 1,
        competenceId: 1,
        competenceTitle: 'Communication',
        title: 'Listens actively before responding',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 5],
    },
    {
        id: 2,
        competenceId: 1,
        competenceTitle: 'Communication',
        title: 'Communicates ideas clearly in writing',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2],
    },
    {
        id: 3,
        competenceId: 1,
        competenceTitle: 'Communication',
        title: 'Gives constructive feedback to peers',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: true,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 5, 6],
    },
    {
        id: 4,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        title: 'Delivers features on time with high quality',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 7],
    },
    {
        id: 5,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        title: 'Writes clean, maintainable code',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2],
    },
    {
        id: 6,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        title: 'Demonstrates strong debugging skills',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: true,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 7],
    },
    {
        id: 7,
        competenceId: 3,
        competenceTitle: 'Leadership',
        title: 'Mentors and supports junior team members',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [5, 6],
    },
    {
        id: 8,
        competenceId: 4,
        competenceTitle: 'Collaboration',
        title: 'Works effectively across different teams',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 4, 5, 6],
    },
    {
        id: 9,
        competenceId: 5,
        competenceTitle: 'Problem Solving',
        title: 'Breaks down complex problems into manageable parts',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 5],
    },
    {
        id: 10,
        competenceId: 1,
        competenceTitle: 'Communication',
        title: "What are this person's key strengths?",
        answerType: AnswerType.TEXT_FIELD,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 4, 5, 6, 7],
    },
    {
        id: 11,
        competenceId: 4,
        competenceTitle: 'Collaboration',
        title: 'What areas could this person improve?',
        answerType: AnswerType.TEXT_FIELD,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ACTIVE,
        positionIds: [1, 2, 4, 5, 6, 7],
    },
    {
        id: 12,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        title: 'Proactively identifies technical debt',
        answerType: AnswerType.NUMERICAL_SCALE,
        isForSelfassessment: false,
        status: QuestionTemplateStatus.ARCHIVED,
        positionIds: [1],
    },
];

// =================== QUESTIONS (for reviews) ===================

export const mockQuestions: Question[] = [
    {
        id: 1,
        cycleId: 1,
        questionTemplateId: 1,
        title: 'Listens actively before responding',
        answerType: AnswerType.NUMERICAL_SCALE,
        competenceId: 1,
        competenceTitle: 'Communication',
        isForSelfassessment: false,
    },
    {
        id: 2,
        cycleId: 1,
        questionTemplateId: 2,
        title: 'Communicates ideas clearly in writing',
        answerType: AnswerType.NUMERICAL_SCALE,
        competenceId: 1,
        competenceTitle: 'Communication',
        isForSelfassessment: false,
    },
    {
        id: 3,
        cycleId: 1,
        questionTemplateId: 4,
        title: 'Delivers features on time with high quality',
        answerType: AnswerType.NUMERICAL_SCALE,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        isForSelfassessment: false,
    },
    {
        id: 4,
        cycleId: 1,
        questionTemplateId: 5,
        title: 'Writes clean, maintainable code',
        answerType: AnswerType.NUMERICAL_SCALE,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        isForSelfassessment: false,
    },
    {
        id: 5,
        cycleId: 1,
        questionTemplateId: 8,
        title: 'Works effectively across different teams',
        answerType: AnswerType.NUMERICAL_SCALE,
        competenceId: 4,
        competenceTitle: 'Collaboration',
        isForSelfassessment: false,
    },
    {
        id: 6,
        cycleId: 1,
        questionTemplateId: 10,
        title: "What are this person's key strengths?",
        answerType: AnswerType.TEXT_FIELD,
        competenceId: 1,
        competenceTitle: 'Communication',
        isForSelfassessment: false,
    },
    {
        id: 7,
        cycleId: 1,
        questionTemplateId: 11,
        title: 'What areas could this person improve?',
        answerType: AnswerType.TEXT_FIELD,
        competenceId: 4,
        competenceTitle: 'Collaboration',
        isForSelfassessment: false,
    },
];

// =================== CLUSTERS ===================

export const mockClusters: Cluster[] = [
    {
        id: 1,
        competenceId: 1,
        competenceTitle: 'Communication',
        lowerBound: 0,
        upperBound: 2,
        title: 'Beginner',
        description: 'Developing basic communication skills',
    },
    {
        id: 2,
        competenceId: 1,
        competenceTitle: 'Communication',
        lowerBound: 2,
        upperBound: 3,
        title: 'Intermediate',
        description: 'Demonstrates adequate communication in most situations',
    },
    {
        id: 3,
        competenceId: 1,
        competenceTitle: 'Communication',
        lowerBound: 3,
        upperBound: 4,
        title: 'Advanced',
        description: 'Strong communicator across various contexts',
    },
    {
        id: 4,
        competenceId: 1,
        competenceTitle: 'Communication',
        lowerBound: 4,
        upperBound: 5,
        title: 'Expert',
        description: 'Exceptional communication skills, role model',
    },
    {
        id: 5,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        lowerBound: 0,
        upperBound: 2,
        title: 'Beginner',
        description: 'Building foundational technical skills',
    },
    {
        id: 6,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        lowerBound: 2,
        upperBound: 4,
        title: 'Proficient',
        description: 'Solid technical contributor',
    },
    {
        id: 7,
        competenceId: 2,
        competenceTitle: 'Technical Excellence',
        lowerBound: 4,
        upperBound: 5,
        title: 'Expert',
        description: 'Technical expert and thought leader',
    },
];
